### PR TITLE
Remove FreeBSD RCSID tags

### PR DESCRIPTION
**Pull request by jlduran**
No functional change.

### CODE REVIEW

**Comment by jlduran** [comment]
Note that the `Makefile` and `HACKING` files now have an empty first line.

**Comment by bsdimp** [comment]
These look good to me. I need to sweep the tree for at least the Makefile pattern

**Review by davidchisnall — APPROVED** [review]

**Comment by davidchisnall** [comment]
Thanks!

**Comment by jlduran** [comment]
> Thanks!

Thank you for the commit access!

**Pull request merged**
