### PR TITLE
Add some discussion about overlays to dtc(1)

### PR DESCRIPTION
**Pull request by kevans91**
- Add an OVERLAYS section to the man page with some background/information on overlays and how they should be created and subsequently used.
- Add some examples relevant to generating and usage of overlays; primarily how to generate a base .dtb that may be amended with overlays, and how to generate an overlay as well as the standard extension to be used for overlays.

I'm bad with words and whatnot, so this might need some heavy editing.

### CODE REVIEW

**Comment by kevans91** [comment]
I should probably note that I clearly have no expectation of this going in before PR #31 given that it references things specifically not supported until PR #31 is merged, and these two PRs together are the last two that I'd like to have merged before I import back to -HEAD.

**Comment by davidchisnall** [comment]
I'll merge now and do an editing pass later: some documentation is better than no documentation!

**Comment by kevans91** [comment]
For what it's worth, I did consider popping it over to the manpages@ group on phabricator before submitting the PR- perhaps it might still not be a bad idea, then I'll just open a new PR with their requested edits?

**Comment by davidchisnall** [comment]
Probably a good idea to get them to do a full pass over the page and open a PR with their proposed edits.

**Pull request merged**
